### ISSUE TITLE
Chaprice issue: comparaison proposed even though charger not referenced in chargeprice, and goingelectric saying it is free

### ISSUE THREAD

**Issue by Altonss** [johan12345/EVMap#248] opened 2022-10-26 20:09 UTC
Location: Camping Le Grand Gravelot, Calais (FR)

**Comment by johan12345** [comment] 2022-10-26 20:59
This specific charger does not have a network/operator listed on GoingElectric, I think that is why it doesn't appear at Chargeprice. So this is a duplicate of #248 and will be fixed with d52ec0c.

There may still be some chargers that GoingElectric shows as free that still have a price comparison button (if all other necessary information such as plug details and network are available). That is to make sure that you can still use the price comparison, e.g.,
- if there is a specific method to activate the charger for free (e.g. during the opening hours of a business), but it also accepts roaming RFID cards/apps for paid charging, or
- in case the GE data is outdated (e.g. the charger has recently changed from free to paid)

**Closed** 2022-10-26 20:59 UTC
Labels: duplicate

**Comment by Altonss** [comment] 2022-10-26 22:30
Oh sorry for the duplicate!
