### ISSUE TITLE
Bug: filter makes the app crash when switching data provider

### ISSUE THREAD

**Issue by Altonss** [johan12345/EVMap#231] opened 2022-09-10 16:09 UTC
Steps to reproduce:
- create filter while using GoingElectric
- enable filter
- filter OpenChargeMap data
- enable the created filter
- the app crashes!

**Comment by Altonss** [comment] 2022-09-10 16:11
In general seing also #229 and #230, the whole filtering logic seems broken... After restarting the app I see the some filter on the map setting, but when entering the filter management menu, it isn't there and another filter is there... so something is messed up in memory :(

**Comment by johan12345** [comment] 2022-09-10 16:25
The filters should be tied to the currently selected data source (because the filter settings that the data sources support are different). So it is expected behavior that filters created with one data source don't appear for the other.

However I think at least part of the problem is that currently switching the data source is not reflected in the map view until after a restart of the app (while the "manage filter profiles" menu does update right away).

**Comment by johan12345** [comment] 2022-09-10 16:35
If I remember correcty, the problem that the data source isn't updated in the map view until restarting the app is already fixed with the restructuring that is part of #164 (which will take some more time to be completed). Probably it makes sense to backport the relevant changes to `master`.

**Comment by johan12345** [comment] 2022-09-11 16:13
Should be fixed with 89b2175d.

**Closed by johan12345** 2022-09-11 16:13 UTC
