### ISSUE TITLE
Feature request: Multiple filters

### ISSUE THREAD

**Issue by theoriginalgri** [johan12345/EVMap#58] opened 2020-09-26 10:25 UTC
Right now, I'm using the filters only for trips (DC and a few providers). Having the option to at least define two filters (AC for example) and select between them and none would be a great feature in my point of view.

**Comment by johan12345** [comment] 2020-09-26 10:40
Yes, this is already planned (#16) and I started working on it on the `filter-profiles` branch. Just don't have so much time to work on EVMap at the moment... :)

**Comment by johan12345** [comment] 2020-09-26 10:41
Closing as duplicate of #16

**Closed by johan12345** 2020-09-26 10:41 UTC
Labels: duplicate
