### ISSUE TITLE
Android Auto/Automotive: Search function while driving

### ISSUE THREAD

**Issue by wkhom** [johan12345/EVMap#262] opened 2022-12-08 06:27 UTC
In current version for AAOS, search function is available but unfortunately not available when driving. Same for the close search button. Can this be changed?

**Comment by johan12345** [comment] 2022-12-08 20:39
The on-screen keyboard for search is not usable while driving - this is a restriction enforced by Google's Car App Library which we can't change. However, the "close search" button can be enabled while driving, I will look into that.

Also, according to the [design guidelines](https://developer.android.com/training/cars/Android%20for%20Cars%20App%20Library%20design%20guidelines.pdf) (page 52), it is supposed to be possible to show at least a search screen with the recent search results even while driving. I see this is working on Android Auto, when you first open the search screen and then start to drive (and I could enable that to work also when opening the search screen while driving).

Could you test on your AAOS car what happens when you do that? In my AAOS emulator it seems like this feature is not implemented, the search screen is completely disabled when you start to drive.

**Comment by johan12345** [comment] 2022-12-08 20:48
> In my AAOS emulator it seems like this feature is not implemented, the search screen is completely disabled when you start to drive.

Ah, I was probably wrong with this observation. That is the case in the Polestar 2 emulator with Android 10 (unfortunately they don't provide a newer emulator image), but it works correctly (i.e. keyboard is disabled, but recent results are shown) on the generic AAOS emulator with Android 11. So I would assume it would also possible to use this feature on an actual AAOS car with up-to-date Android.

**Comment by wkhom** [comment] 2022-12-08 23:16
With Polestar 2 the behavior is as follows:
When I start driving after a search, the search result stay visible, and I can press the Reload button to refresh the results. However, there are no other options regarding search available while driving - all locked. If you want me to test some features, just let me know..
BR, Walter 

BTW: I have checked the Plugshare AAOS app in parallel. They have achieved, that search function including voice input (Google Assistant) is working also when driving. But no idea how it is done.. maybe they do not use Google Template Host

**Comment by johan12345** [comment] 2022-12-09 07:34
What I meant is: Try to start driving while the search screen is open - in that case, you might get the behavior that you also see in Plugshare (recent results show and searching works with voice input, just no keyboard).

If that works correctly on the car, I can also enable the search button itself to work while driving (I did not enable it as it didn't work on the emulator).

**Comment by wkhom** [comment] 2022-12-09 08:50
Ok understood. I will check in early afternoon and send some pics

**Comment by wkhom** [comment] 2022-12-09 14:20
Here we go
![20221209_151158](https://user-images.githubusercontent.com/114795381/206722584-1444b9e9-e22d-434a-950a-3836fff9c84c.jpg)
![20221209_151335](https://user-images.githubusercontent.com/114795381/206722593-6127eeef-65e4-4356-91af-97b10417b0ca.jpg)
![20221209_151448](https://user-images.githubusercontent.com/114795381/206722599-42035d53-69f8-47f8-8f7c-d4e543f8bffe.jpg)
![20221209_151656](https://user-images.githubusercontent.com/114795381/206722607-3fd7b5e3-5684-4bc0-ab3e-5fab6bd580ef.jpg)

**Comment by johan12345** [comment] 2022-12-09 16:29
Okay, thanks! Yes, then it looks like search while driving is indeed implemented by Polestar even though it wasn't working on the emulator. I'll try to enable it in the next update.

**Comment by wkhom** [comment] 2022-12-09 17:42
Sounds great 👍

**Comment by wkhom** [comment] 2022-12-09 17:51
Another topic (should be maybe in a seperate issue):
When checking the price, the app crashes (not always but sometimes). Could not identify under what circumstances. I read similar from another user in the Polestar forum..
https://youtube.com/shorts/yuRhwkUGX3Y?feature=share

**Comment by johan12345** [comment] 2022-12-09 20:44
> Another topic (should be maybe in a seperate issue): When checking the price, the app crashes (not always but sometimes).

Oh yeah, I could now finally reproduce that issue in certain cases. Should also be fixed with the next release with https://github.com/johan12345/EVMap/commit/56712ff1affa4adc11ab98689c1f48774fc788a9 and https://github.com/johan12345/EVMap/commit/c489df2aaff591ccfae248de2c0d4e01acc63194.

**Closed by johan12345** 2022-12-09 20:44 UTC
Labels: api-limitation, android-auto
