### ISSUE TITLE
OpenStreetMap insted of Mapbox

### ISSUE THREAD

**Issue by Florian-Sabonchi** [johan12345/EVMap#169] opened 2022-05-16 14:11 UTC
Hello what do you think to use OpenStreet map instead of mapbox

**Comment by johan12345** [comment] 2022-05-16 14:52
Mapbox maps are based on OpenStreetMap data and their client SDK (at least the older version that we are currently using) is open source. So what exactly are you proposing and what benefit would that bring?

- Using a different client library?
- Using a different OpenStreetMap tile provider?
- Using OpenStreetMap data for charging stations? (this is currently in development, see #97)
- Using a different service for geocoding queries (search field)? 

I already wrote some comments on #36 and #141 that might help understand why we are currently using Mapbox, which other options are available and why some of them are not currently feasible.

**Comment by Florian-Sabonchi** [comment] 2022-05-16 15:23
![Screenshot_20220516-171638](https://user-images.githubusercontent.com/54689374/168627768-1796d884-de6b-48eb-8c0d-855975720e5b.png)

**Comment by Florian-Sabonchi** [comment] 2022-05-16 15:27
I hope you can understand now why I opened this issue
And thank you for your great work

**Comment by johan12345** [comment] 2022-05-16 16:32
Hm okay, yeah, so this tool seems to just detect „trackers“ based on package names, not checking if tracking code is actually included and enabled. As stated in #141 all telemetry is disabled, there are just some concerns about the SKU token which is necessary for billing purposes. So I‘ll close this as a duplicate of #141.

**Closed by johan12345** 2022-05-16 16:32 UTC
